#! /bin/sh

set -e
set -u
set -x

builder=`readlink -f $1`

shift

out=~/coolpkgstore/`echo $@ $(uname -sr) | cat - $builder | sha1sum | cut -f 1 -d ' '`

if test -d $out
then
	if test -f $out/.coolpkg_ok
	then
		echo $out
		exit 0
	else
		rm -rf $out
	fi
fi

builddir=`mktemp -d`
startdir=`pwd`

cd $builddir
mkdir -p $out
if env out="$out" $builder $@ 1>&2
then
	touch $out/.coolpkg_ok
	cd $startdir
 	rm -rf $builddir	
	echo $out
else
	echo "build failed" 1>&2
	rm -rf $builddir
	exit 1
fi
